set-option -g history-limit 3000
set -g mouse

set -g @catppuccin_flavor '$CATPPUCCIN_FLAVOR'
run ~/.config/tmux/plugins/tmux/catppuccin.tmux

# Make the status line more pleasant.
set -g status-left ""
set -g status-right '#[fg=#{@thm_crust},bg=#{@thm_teal}] session: #S '

# Ensure that everything on the right side of the status line
# is included.
set -g status-right-length 100
