[general]
import = [
	"alacritty-theme/themes/catppuccin_latte.toml"
]

[font]
size = 11.0

[font.bold]
family = "MartianMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "MartianMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "MartianMono Nerd Font"
style = "Italic"

[font.normal]
family = "MartianMono Nerd Font"
style = "Regular"
